import { CLEAN_FORBIDDEN_MARKERS, findForbiddenMarker } from "./forbidden-markers";
import type { ExportRenderInput, ExportRenderResult } from "./types";
import { safeFileNamePart } from "./util";

/**
 * Builds the external-facing cover email draft (Milestone 3B).
 *
 * Output format is Markdown, returned as UTF-8 bytes wrapped in the same
 * ExportRenderResult shape the DOCX builders use. Markdown was chosen over
 * DOCX for this artifact because:
 *
 *   - It is text — a lawyer typically pastes the content into Outlook /
 *     Gmail / their email client; they do not attach an email-as-DOCX.
 *   - It is trivially scrubable for forbidden markers (no XML to walk).
 *   - It is smaller and faster.
 *
 * Audience: external. Must contain NO internal commentary, NO Issue Card
 * rationale, NO negotiation guidance. Just a polite Korean business email
 * referencing the project, contract type, version, and source pack.
 *
 * The system NEVER sends the email itself. The output is a draft for a
 * human lawyer to copy / paste / edit / send manually. PLATFORM_BRIEF.md
 * §5 rule 2.
 */
export async function buildCoverEmail(
  input: ExportRenderInput,
): Promise<ExportRenderResult> {
  const project_name = input.project.name;
  const version_number = input.contract_version.version_number;
  const contract_type = input.playbook?.contract_type ?? "계약서";

  const subject = `${project_name} — ${contract_type} 검토안 송부의 건 (${version_number})`;

  const body = [
    `# ${subject}`,
    ``,
    `> 이 문서는 외부 송부용 이메일 초안입니다. **시스템은 이메일을 자동 발송하지 않습니다.** 변호사가 검토 후 직접 발송해 주십시오.`,
    `> This is a draft cover email for external delivery. The system does NOT auto-send. A human lawyer must review and send manually.`,
    ``,
    `---`,
    ``,
    `**제목 / Subject**: ${subject}`,
    ``,
    `안녕하십니까,`,
    ``,
    `${contract_type} 검토안(버전 ${version_number})을 송부드립니다.`,
    `프로젝트: ${project_name}`,
    ``,
    `내용을 검토해 주시기 바라며, 의견이 있으시면 회신 부탁드립니다.`,
    ``,
    `본 검토안은 다음 자료를 토대로 작성되었습니다:`,
    `- Source Pack: ${input.source_pack_id}`,
    `- Playbook: ${input.playbook?.id ?? "(none)"}`,
    `- Contract Version: ${input.contract_version.id}`,
    ``,
    `감사합니다.`,
    ``,
    `---`,
    ``,
    `*Draft generated by ContractOps AI on ${input.generated_at}. External delivery requires a human lawyer's review.*`,
    ``,
  ].join("\n");

  // External scrub: refuse to emit if any internal-commentary marker landed
  // in the output. The body above does not include any Issue Card text, any
  // reviewer rationale, or any negotiation guidance, so this scrub is the
  // safety net for future regressions (e.g. someone adds a "context"
  // section that accidentally pulls in commentary). Same marker list the
  // clean DOCX renderer uses (CLEAN_FORBIDDEN_MARKERS).
  const leak = findForbiddenMarker(body);
  if (leak) {
    throw new Error(
      `cover email render refused: output contains forbidden marker "${leak}". ` +
        "Cover email is external-facing; see PLATFORM_BRIEF.md §5 rules 6/7.",
    );
  }

  const buffer = new TextEncoder().encode(body);
  const file_name = `${safeFileNamePart(project_name)}_${safeFileNamePart(version_number)}_cover_email.md`;

  return {
    buffer,
    file_name,
    mime_type: "text/markdown; charset=utf-8",
  };
}

/** Re-exported for test ergonomics — same list the clean DOCX uses. */
export { CLEAN_FORBIDDEN_MARKERS };
